import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { styled } from '@linaria/react';



const Wrapper = styled.div`
  width: 100vw;
  height: 100vh;
`;

const Container = styled.div`
  width: 100%;
`;

const Button = styled.button`
  
`;



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Box</div>
        <Wrapper>
          <Container>
            <Button>Hello Button</Button>
          </Container>
        </Wrapper>
      </main>
    </>
  )
}
